# --- !Ups

CREATE TABLE "RECETA" (
  "NOMBRE"        VARCHAR NOT NULL PRIMARY KEY,
  "INGREDIENTES"  VARCHAR,
  "INSTRUCCIONES" VARCHAR,
  "IMAGEN"        VARCHAR
);

# --- !Downs

DROP TABLE "RECETA";